on: push
jobs:
  testing-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/hello
        id: issue
        with: 
          token: ${{secrets.GITHUB_TOKEN}}
          title: Example title
          body: Example body
          assignees: |
            agviegas
      - run: |
          echo ${{ steps.issue.outputs.issue }}
